export const Users = [
  {
    id: 1,
    profilePicture: 'person/1.jpeg',
    username: 'Lee Seong Eun',
  },
  {
    id: 2,
    profilePicture: 'person/2.jpeg',
    username: 'Park Youn',
  },
  {
    id: 3,
    profilePicture: 'person/3.jpeg',
    username: 'Lee Jae Jin',
  },
  {
    id: 4,
    profilePicture: 'person/4.jpeg',
    username: 'Kim Al Ji',
  },
  {
    id: 5,
    profilePicture: 'person/5.jpeg',
    username: 'Rionen',
  },
  {
    id: 6,
    profilePicture: 'person/6.jpeg',
    username: 'Kure',
  },
  {
    id: 7,
    profilePicture: 'person/7.jpeg',
    username: 'Yono Miko',
  },
  {
    id: 8,
    profilePicture: 'person/8.jpeg',
    username: 'Kim Eun Ji',
  },
  {
    id: 9,
    profilePicture: 'person/9.jpeg',
    username: 'Yoon Si Won',
  },
  {
    id: 10,
    profilePicture: 'person/10.jpeg',
    username: 'Orenon',
  },
];

export const Posts = [
  {
    id: 1,
    desc: 'Love For All, Hatred For None.',
    photo: 'post/1.jpeg',
    date: '5 mins ago',
    userId: 1,
    like: 32,
    comment: 9,
  },
  {
    id: 2,
    desc: 'kim desc oracle',
    photo: 'post/2.jpeg',
    date: '15 mins ago',
    userId: 2,
    like: 2,
    comment: 1,
  },
  {
    id: 3,
    desc: 'loream dfjkatlmld dfdsafds',
    photo: 'post/3.jpeg',
    date: '20 mins ago',
    userId: 3,
    like: 15,
    comment: 3,
  },
  {
    id: 4,
    desc: 'ktmkdsfa dkvmlsdfmksd',
    photo: 'post/4.jpeg',
    date: '7 mins ago',
    userId: 4,
    like: 11,
    comment: 6,
  },
  {
    id: 5,
    desc: 'nbvcnghfdhgf',
    photo: 'post/5.jpeg',
    date: '23 mins ago',
    userId: 5,
    like: 45,
    comment: 12,
  },
  {
    id: 6,
    desc: 'opyuilojhgkhj hgfdhaedgfdvdzfgs fdsafds',
    photo: 'post/6.jpeg',
    date: '70 mins ago',
    userId: 6,
    like: 32,
    comment: 9,
  },
  {
    id: 7,
    desc: 'hgfnjhyijutjikl lpogkjhk,mhmbn',
    photo: 'post/7.jpeg',
    date: '80 mins ago',
    userId: 7,
    like: 7,
    comment: 9,
  },
  {
    id: 8,
    desc: 'tertqerwe vfdghfdshsdfgd',
    photo: 'post/8.jpeg',
    date: '90 mins ago',
    userId: 8,
    like: 1,
    comment: 9,
  },
  {
    id: 9,
    desc: 'gsdafsadgdfs gbfgsdfgfds',
    photo: 'post/9.jpeg',
    date: '34 mins ago',
    userId: 9,
    like: 2,
    comment: 9,
  },
  {
    id: 10,
    desc: 'puioyokhjgdqwdqw vbdfghdhfg',
    photo: 'post/10.jpeg',
    date: '5 mins ago',
    userId: 10,
    like: 22,
    comment: 9,
  },
];
